apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: backup-data-pvc
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
    volumeName: "dev-data-08"
