apiVersion: v1
kind: PersistentVolume
metadata:
   name: dev-data-02
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteOnce
   rbd:
      monitors:
         - 192.168.128.71:6789
         - 192.168.128.11:6789
      pool: dev-containers
      image: data-ext4-02
      user: kubecluster
      secretRef:
         name: ceph-kubecluster
      fsType: ext4
      readOnly: false
   persistentVolumereclaimPolicy: Recycle
